AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140

AsciiComments:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/PerlBackrefs:
    Enabled: false

Style/Lambda:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enable: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 25

Metrics/MethodLength:
  Max: 25
